// GENERATED — do not edit by hand
// Source: design/brandbook/monroe-livestock/tokens.json
// Generated by: design/compile-tokens.mjs

import 'package:charlotte_ui/theme.dart';
import 'package:flutter/material.dart';

/// MonroeLivestock brand color palette
class MonroeLivestockColors {
  MonroeLivestockColors._();

  static const primary = ColorSwatch9(
    shade100: Color(0xFFC8E6D4),
    shade200: Color(0xFF95CCA9),
    shade300: Color(0xFF63B37F),
    shade400: Color(0xFF3F8F61),
    shade500: Color(0xFF2D6A4F),
    shade600: Color(0xFF24553F),
    shade700: Color(0xFF1B4030),
    shade800: Color(0xFF122B20),
    shade900: Color(0xFF091510),
  );

  static const secondary = ColorSwatch9(
    shade100: Color(0xFFF9E8B8),
    shade200: Color(0xFFF2D06E),
    shade300: Color(0xFFE8B830),
    shade400: Color(0xFFDEAC1F),
    shade500: Color(0xFFD4A017),
    shade600: Color(0xFFAA8012),
    shade700: Color(0xFF7F600E),
    shade800: Color(0xFF554009),
    shade900: Color(0xFF2A2005),
  );

  static const tertiary = ColorSwatch9(
    shade100: Color(0xFFE6D2BF),
    shade200: Color(0xFFCCA580),
    shade300: Color(0xFFB37940),
    shade400: Color(0xFF9A5D27),
    shade500: Color(0xFF8B4513),
    shade600: Color(0xFF6F370F),
    shade700: Color(0xFF53290C),
    shade800: Color(0xFF381C08),
    shade900: Color(0xFF1C0E04),
  );

  static const error = ColorSwatch9(
    shade100: Color(0xFFF5DCDC),
    shade200: Color(0xFFEBB9B9),
    shade300: Color(0xFFE29597),
    shade400: Color(0xFFD87274),
    shade500: Color(0xFFCE4F51),
    shade600: Color(0xFFA53F41),
    shade700: Color(0xFF7C2F31),
    shade800: Color(0xFF522020),
    shade900: Color(0xFF291010),
  );

  static const background = Color(0xFF0F1A14);
  static const surface = Color(0xFF162219);
  static const surfaceVariant = Color(0xFF1E3228);

  static const textPrimary = Color(0xFFE8E4DF);
  static const textSecondary = Color(0xFFE8E4DF).withValues(alpha: 0.7);
  static const textTertiary = Color(0xFF7A8B7E);
  static const textDisabled = Color(0xFF7A8B7E).withValues(alpha: 0.6);
}

/// MonroeLivestock theme configuration
const monroeLivestockThemeConfig = CharlotteThemeConfig(
  primary: MonroeLivestockColors.primary,
  secondary: MonroeLivestockColors.secondary,
  tertiary: MonroeLivestockColors.tertiary,
  error: MonroeLivestockColors.error,
  background: MonroeLivestockColors.background,
  surface: MonroeLivestockColors.surface,
  surfaceVariant: MonroeLivestockColors.surfaceVariant,
  textPrimary: MonroeLivestockColors.textPrimary,
  textSecondary: MonroeLivestockColors.textPrimary,
  textTertiary: MonroeLivestockColors.textTertiary,
  textDisabled: MonroeLivestockColors.textDisabled,
  glassBlurSubtle: 12,
  glassBlurStandard: 24,
  glassBlurFrosted: 40,
  glassBlurDeep: 60,
  glassFillOpacity: 0.1,
  glassBorderOpacity: 0.2,
  headingFontFamily: 'Oswald',
  bodyFontFamily: 'Inter',
  radiusSmall: 10,
  radiusMedium: 16,
  radiusLarge: 22,
);
